AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Models/TopicoViewModel.cs
using KnowledgeBaseForum.AdminWebApp.Models.Enum;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace KnowledgeBaseForum.AdminWebApp.Models
{
    public class TopicoViewModel : BaseViewModel
    {
        /// <summary>
        /// Topic title.
        /// </summary>
        [Display(Name = "Título")]
        public string Titulo { get; set; } = null!;

        /// <summary>
        /// Topic content.
        /// </summary>
        [Display(Name = "Conteúdo")]
        public string Conteudo { get; set; } = null!;

        /// <summary>
        /// Access type (enum).
        /// </summary>
        [Display(Name = "Estado Publicação")]
        public TopicoTipoAcessoEnum TipoAcesso { get; set; }

        /// <summary>
        /// Topic status (active).
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// Author (User) Id.
        /// </summary>
        public string UsuarioId { get; set; } = null!;

        /// <summary>
        /// Comments tied to the topic.
        /// </summary>
        public IEnumerable<ComentarioViewModel>? Comentarios { get; set; }

        /// <summary>
        /// Tags tied to the topic.
        /// </summary>
        [Display(Name = "Tags")]
        [JsonProperty("TopicoTag")]
        public IEnumerable<TopicoTagLink>? TagLinks { get; set; }

        /// <summary>
        /// Author user.
        /// </summary>
        [Display(Name = "Autor")]
        public UsuarioViewModel? Usuario { get; set; }

        /// <summary>
        /// Returns the author's name.
        /// </summary>
        public string? AuthorName => Usuario?.Nome;

        /// <summary>
        /// Returns tag list as string.
        /// </summary>
        public string? Tags => string.Join(", ", TagLinks?.Select(tl => tl.Tag?.Descricao) ?? new string[] { });
    }

    public class TopicoTagLink
    {
        /// <summary>
        /// TBTag Id.
        /// </summary>
        public Guid TagId { get; set; }

        /// <summary>
        /// Topic Id.
        /// </summary>
        public Guid TopicoId { get; set; }

        /// <summary>
        /// Related tag.
        /// </summary>
        public TagViewModel Tag { get; set; } = null!;
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Models/ViewModel/TopicoViewModel.cs
using KnowledgeBaseForum.AdminWebApp.Models.Enum;
using Markdig;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace KnowledgeBaseForum.AdminWebApp.Models.ViewModel
{
    public class TopicoViewModel : BaseViewModel
    {
        /// <summary>
        /// Topic title.
        /// </summary>
        [Display(Name = "Título")]
        public string Titulo { get; set; } = null!;

        /// <summary>
        /// Topic content (raw text).
        /// </summary>
        [Display(Name = "Conteúdo")]
        public string Conteudo { get; set; } = null!;

        /// <summary>
        /// Access type (enum).
        /// </summary>
        [Display(Name = "Estado Publicação")]
        public TopicoTipoAcessoEnum TipoAcesso { get; set; }

        /// <summary>
        /// Topic status (active).
        /// </summary>
        public bool Status { get; set; }

        /// <summary>
        /// Author (User) Id.
        /// </summary>
        public string UsuarioId { get; set; } = null!;

        /// <summary>
        /// Comments tied to the topic.
        /// </summary>
        public IEnumerable<ComentarioViewModel>? Comentarios { get; set; }

        /// <summary>
        /// Tags tied to the topic.
        /// </summary>
        [Display(Name = "Tags")]
        [JsonProperty("TopicoTag")]
        public IEnumerable<TopicoTagLink>? TagLinks { get; set; }

        /// <summary>
        /// Author user.
        /// </summary>
        [Display(Name = "Autor")]
        public UsuarioViewModel? Usuario { get; set; }

        /// <summary>
        /// Returns the author's name.
        /// </summary>
        public string? AuthorName => Usuario?.Nome;

        /// <summary>
        /// Returns tag list as string.
        /// </summary>
        public string? Tags => string.Join(", ", TagLinks?.Select(tl => tl.Tag?.Descricao) ?? new string[] { });

        /// <summary>
        /// Return topic content as HTML rendered from Markdown.
        /// </summary>
        public string ConteudoMarkdown() => Markdown.ToHtml(Conteudo);
    }

    public class TopicoTagLink
    {
        /// <summary>
        /// TBTag Id.
        /// </summary>
        public Guid TagId { get; set; }

        /// <summary>
        /// Topic Id.
        /// </summary>
        public Guid TopicoId { get; set; }

        /// <summary>
        /// Related tag.
        /// </summary>
        public TagViewModel Tag { get; set; } = null!;
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Controllers/ComentarioController.cs
using KnowledgeBaseForum.AdminWebApp.Models.Config;
using KnowledgeBaseForum.AdminWebApp.Models.ViewModel;
using KnowledgeBaseForum.AdminWebApp.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Data;

namespace KnowledgeBaseForum.AdminWebApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class ComentarioController : Controller
    {
        private readonly ApiOptions options;
        private readonly IHttpClientFactory factory;

        public ComentarioController(IHttpClientFactory factory, IOptions<ApiOptions> options)
        {
            this.factory = factory;
            this.options = options.Value;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> ListforTopic(Guid topicId)
        {
                    string? token = this.Request.Cookies.GetTokenFromCookies();
            HttpHelper<IEnumerable<ComentarioViewModel>, object> httpPoster = new HttpHelper<IEnumerable<ComentarioViewModel>, object>(factory, options.ApiHost, token);
            IEnumerable<ComentarioViewModel>? commentsForTopic = await httpPoster.Post($"{options.ApiComentario}/{topicId}", new { });

            return PartialView("_ListComments", commentsForTopic ?? new List<ComentarioViewModel>());
        }

        [HttpPost]
        public async Task<JsonResult> ToggleStatus(Guid id)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<ComentarioViewModel[], ComentarioViewModel> httpGetter = new HttpHelper<ComentarioViewModel[], ComentarioViewModel>(factory, options.ApiHost, token);
                ComentarioViewModel[]? original = await httpGetter.Get($"{options.ApiComentario}?commentId={id}");

                if (original?.Count() == 0)
                {
                    return Json(new { result = false, message = $"Comentário não encontrado" });
                }

                original![0].Status = !original[0].Status;
                HttpHelper<ComentarioViewModel, ComentarioViewModel> httpPutter = new HttpHelper<ComentarioViewModel, ComentarioViewModel>(factory, options.ApiHost, token);
                ComentarioViewModel? updated = await httpPutter.Put(options.ApiComentario, original[0]);

                if (updated == null)
                {
                    return Json(new { result = false, message = $"Comentário não atualizado" });
                }

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = $"Falha não esperada - Detalhes: {ex.Message}" });
            }
        }
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Controllers/TopicoController.cs
using KnowledgeBaseForum.AdminWebApp.Models.Config;
using KnowledgeBaseForum.AdminWebApp.Models.ViewModel;
using KnowledgeBaseForum.AdminWebApp.Utils;
using KnowledgeBaseForum.Commons.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System.Data;
using static KnowledgeBaseForum.AdminWebApp.Utils.StubApi;

namespace KnowledgeBaseForum.AdminWebApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class TopicoController : Controller
    {
        private readonly ApiOptions options;
        private readonly IHttpClientFactory factory;
        private readonly bool stubMode;

        public TopicoController(IConfiguration config, IHttpClientFactory factory, IOptions<ApiOptions> options)
        {
            this.factory = factory;
            this.options = options.Value;
            stubMode = bool.Parse(config[Constants.STUB_MODE]);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> List(string filter)
        {
            IEnumerable<TopicoViewModel> queried;

            if (stubMode)
            {
                queried = SimulateListTopico();
            }
            else
            {
                try
                {
                    string? token = this.Request.Cookies.GetTokenFromCookies();
                    HttpHelper<IEnumerable<TopicoViewModel>, object> httpGetter = new HttpHelper<IEnumerable<TopicoViewModel>, object>(factory, options.ApiHost, token);
                    queried = await httpGetter.Get(options.ApiTopico) ?? new List<TopicoViewModel>();
                }
                catch
                {
                    throw;
                }
            }

            return PartialView("_ListTopics", queried.Where(t => string.IsNullOrEmpty(filter) ||
                                                                 t.Titulo.InvariantContains(filter) ||
                                                                 (t.TagLinks?.Any(tl => (tl.Tag?.Descricao?.InvariantContains(filter)).GetValueOrDefault())).GetValueOrDefault()));
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            TopicoViewModel? original;
            SelectList selectListForTags;

            if (stubMode)
            {
                original = SimulateGetTopico(id)!;
                selectListForTags = new SelectList(SimulateListTags(), "Id", "Descricao");
            }
            else
            {
                try
                {
                    string? token = this.Request.Cookies.GetTokenFromCookies();
                    HttpHelper<TopicoViewModel, object> httpGetter = new HttpHelper<TopicoViewModel, object>(factory, options.ApiHost, token);
                    original = await httpGetter.Get($"{options.ApiTopico}/{id}");
                    IEnumerable<TagViewModel>? tags = await new HttpHelper<IEnumerable<TagViewModel>, object>(factory, options.ApiHost, token).Get(options.ApiTags);
                    selectListForTags = new SelectList(tags, "Id", "Descricao");
                }
                catch
                {
                    throw;
                }
            }

            ViewData["TagSelect"] = selectListForTags;
            return View(original);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TopicoViewModel topico)
        {
            TopicoViewModel? original;
            IEnumerable<Guid> selectedTags = ((string)this.Request.Form["tags"])?.Split(",")?.Select(s => new Guid(s)) ?? new Guid[] { };

            if (stubMode)
            {
                original = SimulateGetTopico(topico.Id)!;
                IEnumerable<TagViewModel> tagData = SimulateListTags().Where(t => (selectedTags?.Contains(t.Id)).GetValueOrDefault()).ToList();
                original.TagLinks = selectedTags?.Select(t => new TopicoTagLink() { TagId = t, TopicoId = original.Id, Tag = tagData.First(td => td.Id == t) });
                SimulateEditTopico(topico);
            }
            else
            {
                try
                {
                    string? token = this.Request.Cookies.GetTokenFromCookies();
                    original = await new HttpHelper<TopicoViewModel, object>(factory, options.ApiHost, token).Get($"{options.ApiTopico}/{topico.Id}");

                    if (original == null)
                    {
                        return NotFound();
                    }

                    bool success = true;
                    List<string?> results = new List<string?>();
                    HttpHelper<string, object> httpHelper = new HttpHelper<string, object>(factory, options.ApiHost, token);

                    foreach (Guid tagId in selectedTags.Where(tag => !(original?.TagLinks?.Select(tl => tl.TagId).Contains(tag)).GetValueOrDefault()))
                    {
                        string? result = await httpHelper.Post($"{options.ApiRelationalTopicoTag}?tagId={tagId}&topicId={original?.Id}", new { tagId, topicId = original?.Id });
                        success &= ProcessRelationOutput(results, result);
                    }

                    foreach (Guid tagId in (original?.TagLinks?.Where(tl => !selectedTags.Contains(tl.TagId)).Select(tl => tl.TagId) ?? new Guid[] { }))
                    {
                        string? result = await httpHelper.Delete($"{options.ApiRelationalTopicoTag}?tagId={tagId}&topicId={original?.Id}");
                        success &= ProcessRelationOutput(results, result);
                    }

                    ViewData["Errors"] = results.Where(res => !(res?.InvariantEquals("true")).GetValueOrDefault());
                }
                catch
                {
                    throw;
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<JsonResult> ToggleActivation(Guid id, bool status)
        {
            bool result = true;
            TopicoViewModel? original = null;

            if (stubMode)
            {
                original = SimulateGetTopico(id)!;
                original.Status = !status;
                SimulateEditTopico(original);
            }
            else
            {
                try
                {
                    string? token = this.Request.Cookies.GetTokenFromCookies();
                    
                    if (status)
                    {
                        HttpHelper<bool, object> httpHelper = new HttpHelper<bool, object>(factory, options.ApiHost, token);
                        result = await httpHelper.Delete($"{options.ApiTopico}/{id}");
                    }
                    else
                    {
                        HttpHelper<TopicoViewModel, object> httpHelper = new HttpHelper<TopicoViewModel, object>(factory, options.ApiHost, token);
                        original = await httpHelper.Get($"{options.ApiTopico}/{id}");

                        if (original != null)
                        {
                            original.Status = true;
                            result = await httpHelper.Put($"{options.ApiTopico}/{id}", original) != null;
                        }
                        else
                        {
                            result = false;
                        }
                    }
                }
                catch
                {
                    throw;
                }
            }

            return Json(new { result });
        }

        private bool ProcessRelationOutput(List<string?> list, string? result)
        {
            list.Add(result);
            bool.TryParse(result, out bool resBool);
            return resBool;
        }
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Views/Topico/Edit.cshtml
@model TopicoViewModel

@{
    ViewData["Title"] = "Edição de Tópico";
    List<string>? foundTagIds = Model.TagLinks?.Select(tl => tl.TagId.ToString())?.ToList();
    string? selectedTags = foundTagIds?.Count() > 0 ? $"['{string.Join("', '", foundTagIds)}']" : "null";
}

<h4>Tópico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <div class="col-sm-12">
            <strong>
                <label asp-for="Titulo" class="control-label"></label>
            </strong>
        </div>
        <div class="mx-3">@(Model.Titulo)</div>
    </div>
    <div class="col-md-4">
        <div class="col-sm-12">
            <strong>
                <label asp-for="TipoAcesso" class="control-label col-sm-12"></label>
            </strong>
        </div>
        <div class="mx-3">@(Model.TipoAcesso)</div>
    </div>
    <div class="col-md-4">
        <div class="col-sm-12">
            <strong>
                <label asp-for="Usuario" class="control-label col-sm-12"></label>
            </strong>
        </div>
        <div class="mx-3">@(Model.AuthorName)</div>
    </div>
</div>
<div class="row mt-2">
    <div class="col-md-4">
        <div class="col-sm-12">
            <strong>
                <label asp-for="DataCriacao" class="control-label"></label>
            </strong>
        </div>
        <div class="mx-3">@(Model.DataCriacao)</div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 form-group">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" class="form-control" />
            <input type="hidden" asp-for="Status" class="form-control" />
            <strong>
                <label class="control-label col-sm-12">Tags</label>
            </strong>
            <div class="mt-2 mb-1">
                <select class="form-select multiple" id="tags" name="tags" asp-items="@((SelectList?)ViewData["TagSelect"])" multiple></select>
            </div>
            <br />
            <div class="float-end">
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
                <input type="submit" value="Salvar" class="btn btn-primary mr-2" />
            </div>
        </form>
    </div>
</div>
<hr />
<div class="row mt-2">
    <div class="col-md-12">
        <div class="accordion accordion-flush" id="topicAccordion">
            <div class="accordion-item">
                <h2 class="accordion-header" id="commentHeader">
                    <button class="accordion-button collapsed"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#commentCollapse"
                            aria-expanded="false"
                            aria-controls="commentCollapse">
                        Comentários do Tópico
                    </button>
                </h2>
                <div id="commentCollapse" class="accordion-collapse collapse" aria-labelledby="commentHeader" @*data-bs-parent="#topicAccordion"*@>
                    <div class="accordion-body" id="ajaxComment"></div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="contentHeader">
                    <button class="accordion-button collapsed"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#contentCollapse"
                            aria-expanded="false"
                            aria-controls="contentCollapse">
                        Visualização de Conteúdo do Tópico
                    </button>
                </h2>
                <div id="contentCollapse" class="accordion-collapse collapse" aria-labelledby="contentHeader" @*data-bs-parent="#topicAccordion"*@>
                    <div class="accordion-body">
                        @Html.Raw(Model.ConteudoMarkdown())
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        const getCommentsForTopic = function () {
            const topicId = '@(Model.Id)';

            $.post('@Url.Action("ListforTopic", "Comentario")', { topicId: topicId }, function (data, status) {
                $('#ajaxComment').html(data);
            });
        };

        const toggleComment = function (id) {
            $.post('@Url.Action("ToggleStatus", "Comentario")', { id: id }, function (data, status) {
                getCommentsForTopic();
            });
        };

        $(document).ready(function () {
            const selectedTags = @Html.Raw(selectedTags);
            $('#tags').val(selectedTags);
            $('#tags').select2();
            getCommentsForTopic();
        });
    </script>
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Views/Topico/Index.cshtml
@{
    ViewData["Title"] = "Gerenciamento de Tópicos";
}

<h3>Tópico</h3>
@*<br />
<div class="row"">
    <div class="form-group col-sm-4">
        <label for="countPerPage">N.º de usuários por página</label>
        <select class="form-select" name="countPerPage" id="countPerPage">
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="50">50</option>
            <option value="100">100</option>
            <option value="200">200</option>
        </select>
    </div>
    <div class="form-group col-sm-4">
        <label for="topicFilter">Filtro (Título ou tag)</label>
        <input type="text" class="form-control" name="topicFilter" id="topicFilter" />
    </div>
    <div class="form-group col-sm-4">
        <button role="button" class="btn btn-primary mt-4" style="width: 100px;" id="searchBtn">Buscar</button>
    </div>
</div>*@
<hr />
<div class="row" id="searchResults">
    <div class="d-flex justify-content-center align-middle">
        <div class="spinner-border text-secondary" role="status">
            <span class="sr-only"></span>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        const getTopicData = function (){
            const filter = $('#topicFilter').val();
            const filterDefined = filter !== '' || filter !== null || filter !== undefined;
            const jsonData = {
                filter: (filterDefined ? filter : null)
            };
            $.post('@Url.Action("List", "Topico")', jsonData, function(data, status){
                $('#searchResults').html(data);
                $('#datatable').DataTable({
                    paging: true,
                    processing: true,
                    columns: [
                        { orderable: true },
                        { orderable: true },
                        { orderable: true },
                        { orderable: true },
                        { orderable: true },
                        { orderable: true },
                        { orderable: false }
                    ],
                    language: {
                        decimal: ",",
                        emptyTable: "Não há dados disponíveis",
                        info: "Com _START_ até _END_ de _TOTAL_ registros",
                        infoEmpty: "Sem registros",
                        infoFiltered: "(filtrado com _MAX_ total de registros)",
                        infoPostFix: "",
                        thousands: ".",
                        lengthMenu: "Por página _MENU_",
                        loadingRecords: "Carregando dados...",
                        processing: "",
                        search: "Buscar:",
                        zeroRecords: "Sem dados relacionados encontrados",
                        paginate: {
                            first: "Primeiro",
                            last: "Último",
                            next: "Próximo",
                            previous: "Anterior"
                        },
                        aria: {
                            sortAscending: ": ordem crescente",
                            sortDescending: ": ordem decrescente"
                        }
                    }
                });
            });
        };

        const activationToggle = function(_id, _status)
        {
            const jsonData = { id: _id, status: _status };
            $.post('@Url.Action("ToggleActivation", "Topico")', jsonData, function(data, status){
                $('#topicFilter').val('');
                getTopicData();
            });
        }

        $(document).ready(function(){
            getTopicData();
            $('#searchBtn').click(getTopicData);
        });
    </script>
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Views/Topico/_ListTopics.cshtml
@model IEnumerable<TopicoViewModel>

<table class="table" id="datatable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoAcesso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TagLinks)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="table-striped table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoAcesso)
                </td>
                <td>
                    @if (item.Status)
                    {
                        <strong class="text-success">Ativo</strong>
                    }
                    else
                    {
                        <strong class="text-secondary">Inativo</strong>
                    }
                </td>
                <td>
                    @(item.AuthorName)
                </td>
                <td class="text-primary">
                    @(item.Tags)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCriacao)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary mr-2">
                        <i class="bi bi-pencil-square"></i> Editar
                    </a>
                    @if (item.Status)
                    {
                        <button id="altActivateBtn" class="btn btn-sm btn-outline-danger" onclick="activationToggle('@(item.Id)', @(item.Status.ToString().ToLower()))">
                            <i class="bi bi-x-circle"></i> Desativar
                        </button>
                    }
                    else
                    {
                        <button id="altActivateBtn" class="btn btn-sm btn-outline-success" onclick="activationToggle('@(item.Id)', @(item.Status.ToString().ToLower()))">
                            <i class="bi bi-check-circle"></i> Ativar
                        </button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>