AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Controllers/GrupoController.cs
using KnowledgeBaseForum.AdminWebApp.Models.Config;
using KnowledgeBaseForum.AdminWebApp.Models.ViewModel;
using KnowledgeBaseForum.AdminWebApp.Utils;
using KnowledgeBaseForum.Commons.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Data;
using static KnowledgeBaseForum.AdminWebApp.Utils.Utils;

namespace KnowledgeBaseForum.AdminWebApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class GrupoController : Controller
    {
        private const string UPDATE_FAILURE_MSG = "Falha na atualização";
        private readonly ApiOptions options;
        private readonly IHttpClientFactory factory;

        public GrupoController(IConfiguration config, IHttpClientFactory factory, IOptions<ApiOptions> options)
        {
            this.options = options.Value;
            this.factory = factory;

        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> List(string filter)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<IEnumerable<GrupoViewModel>, object> httpGetter = new HttpHelper<IEnumerable<GrupoViewModel>, object>(factory, options.ApiHost, token);
                IEnumerable<GrupoViewModel> queried = await httpGetter.Get(options.ApiGrupo) ?? new List<GrupoViewModel>();

                return PartialView("_ListGroups", queried.Where(g => string.IsNullOrEmpty(filter) ||
                                                                    g.Descricao.InvariantContains(filter)));
            }
            catch
            {
                throw;
            }
        }

        public async Task<IActionResult> Create()
        {
            string? token = this.Request.Cookies.GetTokenFromCookies();
            List<UsuarioViewModel> allUsers = await new HttpHelper<List<UsuarioViewModel>, object>(factory, options.ApiHost, token).Get(options.ApiUsuario) ??
                                              new List<UsuarioViewModel>();
            ViewData["Users"] = allUsers.ToDictionary(user => user.Login, user => user.Nome);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(GrupoViewModel grupo)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<GrupoViewModel, object> httpPoster = new HttpHelper<GrupoViewModel, object>(factory, options.ApiHost, token);
                grupo.DataCriacao = DateTime.Now;
                grupo.Status = true;
                grupo.UsuarioCriacao = this.User.Claims.GetUserNameFromClaims()!;
                GrupoViewModel? created = await httpPoster.Post(options.ApiGrupo, grupo);

                if (created == null)
                {
                    ViewData["Error"] = "Falha na criação";
                    return View(grupo);
                }

                List<string> selectedUsers = this.Request.Form.Where(f => f.Key.Contains("user_")).Select(f => f.Value.ToString()).ToList();

                if (selectedUsers.Count() > 0)
                {
                    HttpHelper<string, object> httpRelPoster = new HttpHelper<string, object>(factory, options.ApiHost, token);
                    List<string?> results = new List<string?>();
                    bool success = true;

                    foreach (string user in selectedUsers)
                    {
                        string? result = await httpRelPoster.Post($"{options.ApiRelationalUsuarioGrupo}?login={user}&groupId={created!.Id}", new { });
                        success &= ProcessRelationOutput(results, result);
                    }

                    ViewData["Error"] = results.Where(res => !(res?.InvariantEquals("true")).GetValueOrDefault());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<GrupoViewModel, GrupoViewModel> httpGetter = new HttpHelper<GrupoViewModel, GrupoViewModel>(factory, options.ApiHost, token);
                GrupoViewModel? original = await httpGetter.Get($"{options.ApiGrupo}/{id}");

                if (original == null)
                {
                    ViewData["Error"] = "Grupo não foi encontrado";
                    RedirectToAction("Index");
                }
                
                List<UsuarioViewModel> allUsers = await new HttpHelper<List<UsuarioViewModel>, object>(factory, options.ApiHost, token).Get(options.ApiUsuario) ??
                                              new List<UsuarioViewModel>();
                ViewData["Users"] = allUsers.ToDictionary(user => user.Login, user => user.Nome);

                return View(original);
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GrupoViewModel grupo)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<GrupoViewModel, GrupoViewModel> httpHelper = new HttpHelper<GrupoViewModel, GrupoViewModel>(factory, options.ApiHost, token);
                grupo.DataModificacao = DateTime.Now;
                grupo.UsuarioModificacao = this.User.Claims.GetUserNameFromClaims();
                GrupoViewModel? editedGrupo = await httpHelper.Put(options.ApiGrupo, grupo);

                if (editedGrupo == null)
                {
                    throw new Exception(UPDATE_FAILURE_MSG);
                }

                HttpHelper<string, object> httpRelHelper = new HttpHelper<string, object>(factory, options.ApiHost, token);
                string? resultDelAll = await httpRelHelper.Delete($"{options.ApiRelationalUsuarioGrupo}/{grupo.Id}");

                if (!(resultDelAll?.Equals("true")).GetValueOrDefault())
                {
                    throw new Exception(UPDATE_FAILURE_MSG);
                }


                List<string> selectedUsers = this.Request.Form.Where(f => f.Key.Contains("user_")).Select(f => f.Value.ToString()).ToList();

                if (selectedUsers.Count() > 0)
                {
                    HttpHelper<string, object> httpRelPoster = new HttpHelper<string, object>(factory, options.ApiHost, token);
                    List<string?> results = new List<string?>();
                    bool success = true;

                    foreach (string user in selectedUsers)
                    {
                        string? result = await httpRelPoster.Post($"{options.ApiRelationalUsuarioGrupo}?login={user}&groupId={grupo.Id}", new { });
                        success &= ProcessRelationOutput(results, result);
                    }

                    ViewData["Error"] = results.Where(res => !(res?.InvariantEquals("true")).GetValueOrDefault());
                }
                
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains(UPDATE_FAILURE_MSG))
                {
                    ViewData["Error"] = ex.Message;
                    return View(grupo);
                }
                else
                {
                    throw;
                }
            }
        }

        [HttpPost]
        public async Task<JsonResult> ToggleActivation(string id, bool status)
        {
            try
            {
                bool result = true;
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<bool, object> httpHelper = new HttpHelper<bool, object>(factory, options.ApiHost, token);

                if (status)
                {
                    result = await httpHelper.Delete($"{options.ApiGrupo}/{id}");
                }
                else
                {
                    result = await httpHelper.Put($"{options.ApiGrupo}/{id}", new { });
                }

                return Json(new { result });
            }
            catch
            {
                throw;
            }
        }

        private bool ProcessRelationOutput(List<string?> list, string? result)
        {
            list.Add(result);
            bool.TryParse(result, out bool resBool);
            return resBool;
        }
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Controllers/TagController.cs
using KnowledgeBaseForum.AdminWebApp.Models.Config;
using KnowledgeBaseForum.AdminWebApp.Models.ViewModel;
using KnowledgeBaseForum.AdminWebApp.Utils;
using KnowledgeBaseForum.Commons.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Data;
using System.Security.Claims;

namespace KnowledgeBaseForum.AdminWebApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class TagController : Controller
    {
        private readonly ApiOptions options;
        private readonly IHttpClientFactory factory;

        public TagController(IConfiguration config, IHttpClientFactory factory, IOptions<ApiOptions> options)
        {
            this.factory = factory;
            this.options = options.Value;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public async Task<IActionResult> List(string filter)
        {
            string? token = this.Request.Cookies.GetTokenFromCookies();
            IEnumerable<TagViewModel>? tagList = await new HttpHelper<IEnumerable<TagViewModel>, object>(factory, options.ApiHost, token).Get(options.ApiTags);

            return PartialView("_ListTags", tagList?.Where(t => string.IsNullOrEmpty(filter) || t.Descricao.InvariantContains(filter)) ?? new List<TagViewModel>());
        }

        [HttpPost]
        public async Task<JsonResult> Edit(Guid id, string name)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<TagViewModel, TagViewModel> httpHelper = new HttpHelper<TagViewModel, TagViewModel>(factory, options.ApiHost, token);
                TagViewModel? toEdit = await httpHelper.Get($"{options.ApiTags}/{id}");

                if (toEdit == null)
                {
                    return Json(new { result = false, message = "Tag não foi encontrada" });
                }

                toEdit.Descricao = name;
                TagViewModel? result = await httpHelper.Put(options.ApiTags, toEdit);

                if (result != null)
                {
                    return Json(new { result = true });
                }
                else
                {
                    return Json(new { result = true, message = "Falha na atualização do registro." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = $"Falha não esperada: {ex.Message}" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(Guid id)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<object, object> httpHelper = new HttpHelper<object, object>(factory, options.ApiHost, token);
                await httpHelper.Delete($"{options.ApiRelationalTopicoTag}/{id}");
                await httpHelper.Delete($"{options.ApiTags}/{id}");

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = $"Falha não esperada: {ex.Message}" });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Create(string name)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                string username = this.User.Claims.First(c => c.Type.Equals(ClaimTypes.Name)).Value;
                TagViewModel toCreate = new()
                {
                    Descricao = name,
                    UsuarioCriacao = username
                };
                TagViewModel? created = await new HttpHelper<TagViewModel, object>(factory, options.ApiHost, token).Post(options.ApiTags, toCreate);

                if (created == null)
                {
                    return Json(new { result = false, message = $"Falha na criação da Tag." });
                }

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = $"Falha não esperada: {ex.Message}" });
            }
        }
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Controllers/UsuarioController.cs
using KnowledgeBaseForum.AdminWebApp.Models.Config;
using KnowledgeBaseForum.AdminWebApp.Models.ViewModel;
using KnowledgeBaseForum.AdminWebApp.Utils;
using KnowledgeBaseForum.Commons.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using static KnowledgeBaseForum.AdminWebApp.Utils.Utils;

namespace KnowledgeBaseForum.AdminWebApp.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class UsuarioController : Controller
    {
        private readonly ApiOptions options;
        private readonly IHttpClientFactory factory;

        public UsuarioController(IConfiguration config, IHttpClientFactory factory, IOptions<ApiOptions> options)
        {
            this.options = options.Value;
            this.factory = factory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> List(string filter)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<IEnumerable<UsuarioViewModel>, object> httpGetter = new HttpHelper<IEnumerable<UsuarioViewModel>, object>(factory, options.ApiHost, token);
                IEnumerable<UsuarioViewModel> queried = await httpGetter.Get(options.ApiUsuario) ?? new List<UsuarioViewModel>();

                return PartialView("_ListUsers", queried.Where(u => string.IsNullOrEmpty(filter) ||
                                                                    u.Nome.InvariantContains(filter) ||
                                                                    u.Email.InvariantContains(filter) ||
                                                                    u.Login.InvariantContains(filter)));
            }
            catch
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<UsuarioViewModel, object> httpGetter = new HttpHelper<UsuarioViewModel, object>(factory, options.ApiHost, token);
                UsuarioViewModel? usuario = await httpGetter.Get($"{options.ApiUsuario}/{id}");

                return View(usuario);
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UsuarioViewModel usuario)
        {
            try
            {
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<UsuarioViewModel, object> httpHelper = new HttpHelper<UsuarioViewModel, object>(factory, options.ApiHost, token);
                UsuarioViewModel? editedUsuario = await httpHelper.Patch(options.ApiUsuario, usuario);

                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<JsonResult> ToggleActivation(string id, bool status)
        {
            try
            {
                bool result = true;
                string? token = this.Request.Cookies.GetTokenFromCookies();
                HttpHelper<bool, object> httpHelper = new HttpHelper<bool, object>(factory, options.ApiHost, token);
                result = status ? await httpHelper.Delete($"{options.ApiUsuario}/{id}") : await httpHelper.Put($"{options.ApiUsuario}/{id}", new { });

                return Json(new { result });
            }
            catch
            {
                throw;
            }
        }
    }
}

AceleraAtos_ProjFinal_KBF/KnowledgeBaseForum.AdminWebApp/Views/Shared/_Layout.cshtml
@{
    bool isAdmin = this.User.Claims.Any(c => c.Value.Equals("ADMIN"));
    string userGivenName = this.User.Claims.GetGivenNameFromClaims() ?? "Usuário";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fórum de Base de Conhecimento</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons-1.10.3/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KnowledgeBaseForum.AdminWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3 shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-white me-5" asp-area="" asp-controller="Home" asp-action="Index">Plataforma Administrativa</a> 
                <span class="nav-text text-white mt-1">Olá@($" {userGivenName}")!</span>
                <div class="navbar-collapse collapse justify-content-between">
                    <ul class="navbar-nav ms-auto mt-1">
                        @if (isAdmin)
                        {
                            <li class="nav-item me-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="Index">
                                    <i class="bi bi-people"></i> Usuários
                                </a>
                            </li>
                            <li class="nav-item me-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Topico" asp-action="Index">
                                    <i class="bi bi-file-earmark-richtext me-1"></i> Tópicos
                                </a>
                            </li>
                            @*<li class="nav-item me-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Grupo" asp-action="Index">
                                    <i class="bi bi-diagram-3"></i> Grupos
                                </a>
                            </li>*@
                            <li class="nav-item me-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Tag" asp-action="Index">
                                    <i class="bi bi-tags"></i> Tags
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Logout">
                                    <i class="bi bi-person-x"></i> Logout
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Login">
                                    <i class="bi bi-person-up"></i> Login
                                </a>
                            </li>                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark fixed-bottom py-1 shadow-lg">
        <div class="container">
            &copy; 2023 - Fórum de Base de Conhecimento@* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/datatables.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>